-- SQLite
CREATE TABLE IF NOT EXISTS cards (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT NOT NULL,
  color TEXT NULL,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS entries (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  card_id INTEGER NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('EXPENSE', 'INVESTMENT')),
  description TEXT NULL,
  amount NUMERIC(12,2) NOT NULL,
  date TEXT NOT NULL,                  -- ou DATE, mas no SQLite é armazenado como TEXT
  category TEXT NULL,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY (card_id) REFERENCES cards(id) ON DELETE CASCADE
);
